### ISSUE TITLE
GitHub Classrrom Issue

### ISSUE THREAD

**Issue by devgustavovasquez** [quavedev/code-challenge#6]
Trying to access the Classroom's link at the end of the README, but this warning appeared:

![image](https://github.com/quavedev/code-challenge/assets/78443398/7907b7ce-b249-444c-ba62-b3f76de15602)

I already tried logging out and clearing cache, but it didn't work.

**Comment by LucasBeneti** [comment]
I'm having this same issue with the classroom repo access.

**Comment by PabloSSena** [comment]
Me too

**Comment by tiagosn01** [comment]
Same

**Comment by filipenevola** [comment]
I'm not sure what exactly caused the issue here, but candidates are completing the challenge every day, so I'll close this issue.
