### ISSUE TITLE
Clarification needed for code challenge 

### ISSUE THREAD

**Issue by IamManchanda** [quavedev/code-challenge#8]
So I was looking to solve this code challenge but I need one clarification for below task:

```
Between the event selector and the list of people we want to see a summary like this:

- People in the event right now: 10;
- People by company in the event right now: Green Group (10), Hoppe Group (5);
```

I would like to clarify the **"in the event right now"** wording. Does it mean to render all the people registered in the selected event (people collection) or does it mean to render just the ones who are checked in to the event?

Reason why I am asking this is because if it is for all the people registered in the selected event then it would mean that we would be rendering all the items (250+ or so per selected event) even before any user selections for below text as can seen in below image. Is that correct?

```
People by company in the event right now: Green Group (10), Hoppe Group (5);
```

<img width="1728" alt="Screenshot 2024-03-06 at 4 21 44 PM" src="https://github.com/quavedev/code-challenge/assets/4970624/f4b1c38f-7d11-4ca9-84d4-d2a26b92e837">

---

I mean that If I render all items, it will look something like this below. Is this expected?

<img width="1728" alt="Screenshot 2024-03-06 at 4 32 29 PM" src="https://github.com/quavedev/code-challenge/assets/4970624/19be0e08-7d73-46f0-a198-5008147bef4d">

PS: of course styling can be updated in such case. 

---

Thanks & Regards,
Harman Singh Manchanda (Harry Manchanda)

**Comment by filipenevola** [comment]
Hi, we don't answer any questions. We will also assess your interpretation of the requirements, and then we need to measure everybody with the same level of info provided ;)
